MAIN_LOCATION = "SAKRA_ACCOUNTS"
PARENT_FOLDER = r"D:\DEVELOPMENT\SKRA-DMS"
MAIN_TYPE = "Accounts"
SUB_CATEGORIES = ["FIXED ASSET", "IP", "OP", "PRS"]
CREATE_LOCATION = True
APPEND = False
DELETE_IMAGES = False
CREATE_SEPARATE_BIF = False
